### ISSUE TITLE
Version 2 compatibility

### ISSUE THREAD

**Issue by bencroker** [markhuot/craft-pest-core#33]
Great to see [2.0.0](https://github.com/markhuot/craft-pest-core/releases/tag/2.0.0) released, thank you!! I’m struggling with package conflicts, which I thought might have to do with Pest 3. Have you managed to install it with Craft 5 and idea what I might be missing?

![screenshot-pueJWnkF@2x](https://github.com/user-attachments/assets/bc992bea-5283-4e37-94bc-d3214d9fd4a3)

![screenshot-U11SCOIM@2x](https://github.com/user-attachments/assets/f9f935a2-d702-462b-9a91-018c918a4ef0)

**Comment by markhuot** [comment]
Hum, I got a clean install here, https://github.com/markhuot/craft-pest-core/actions/runs/11113757425/job/30878789230. Do you have `yii2-shell` installed, by change?
